### ISSUE TITLE
Error in post-command-hook (ivy--queue-exhibit): (wrong-type-argument listp t)

### ISSUE THREAD

**Issue by jcs090218** [abo-abo/swiper#2540]
I got this error while starting `ivy` minbuffer. Is there something wrong with the recent commits?

Current version: `20200501.1526`

Thanks!

**Comment by basil-conto** [comment]
Please check whether commit 0e4a55f9a1d7dab6a875cc26ad17dc460a98c443 that was pushed one hour ago and/or PR #2539 fixes the issue for you.

**Comment by jcs090218** [comment]
Great! Thanks!

**Comment by jcs090218** [comment]
@basil-conto I still get this error? You sure this is fixed?

**Comment by basil-conto** [comment]
> You sure this is fixed?

No, and in my hurry yesterday I didn't realise the error message in the issue title is different to the one I referenced. You submitted this issue at the exact same time as I was looking at the other error, so I conflated the two. Sorry about that.

Since I have not yet run into your `listp` error, I won't be able to debug it without your help.  Please try figuring out which precise steps lead to the error, so that we can narrow down where it's happening, and why. To rule out your own Emacs configuration and packages, try reproducing the error starting from `make plain` (from within a checkout of this repository) or from `emacs -Q`. TIA.

**Comment by jcs090218** [comment]
IOnce I have this in config, issue appears.

`(setq ivy-auto-shrink-minibuffer t)`

commit is here => https://github.com/abo-abo/swiper/commit/188349971bc08640ae632fd109b1bf2b88306be6

I think the variable `ivy-auto-shrink-minibuffer` is no longer use and should use `ivy-auto-shrink-minibuffer-alist` instead?

**Comment by basil-conto** [comment]
> I think the variable `ivy-auto-shrink-minibuffer` is no longer use and should use `ivy-auto-shrink-minibuffer-alist instead`?

Indeed, the variable `ivy-auto-shrink-minibuffer` is now obsolete and you should customise `ivy-auto-shrink-minibuffer-alist` instead.

The cause of this bug is that `ivy-auto-shrink-minibuffer` was kept as an obsolete [varalias](https://www.gnu.org/software/emacs/manual/html_node/elisp/Variable-Aliases.html) of `ivy-auto-shrink-minibuffer-alist`, which isn't right, since their types are incompatible (one is a boolean, the other an alist). Should be fixed now.

**Comment by jjaone** [comment]
I still encountered this bug using "ivy  20230410.1815 dependency  in Emacs 26.3 in Linux/Ubuntu 20.04 LTS when trying to C-s search with string starting with "** " characters, below error appears (for few seconds, and the disappers):
`Error in post-command-hook (ivy--queue-exhibit): (wrong-type-argument integer-or-marker-p nil)`

After that the ivy-based search does not work anymore.

Was able to work-around this bug by commenting out  "enable-recursive-minibuffers nil" -line:
```
(use-package ivy
  :ensure t
  :init (ivy-mode 1)
  :bind (("C-c C-r"     . 'ivy-resume)             ;; remember/return to last session
         ;;("<tab>"       . 'ivy-partial-or-done)    ;;MUST DEFINE in IVY-MB-MAP
	 ;;("C-j"         . 'ivy-alt-done)           ;;MUST DEFINE in IVY-MB-MAP
	 ;;("<backtab>"   . 'ivy-partial)            ;;TODO: what is this for?
	 ("C-x b"       . 'ivy-switch-buffer))     ;;
  :config (setq ivy-use-virtual-buffers t
		;;enable-recursive-minibuffers nil
		ivy-use-selectable-prompt t
		ivy-display-style 'fancy
		ivy-count-format "(%d/%d) "
		ivy-wrap t)
  (define-key ivy-minibuffer-map (kbd "<tab>") 'ivy-partial-or-done)
  (define-key ivy-minibuffer-map (kbd "C-j") 'ivy-alt-done)
  (define-key ivy-minibuffer-map (kbd "<backtab>") 'ivy-partial)
  )
```

**Comment by basil-conto** [comment]
> I still encountered this bug using "ivy 20230410.1815 dependency in Emacs 26.3 in Linux/Ubuntu 20.04 LTS when trying to C-s search with string starting with "** " characters, below error appears (for few seconds, and the disappers): `Error in post-command-hook (ivy--queue-exhibit): (wrong-type-argument integer-or-marker-p nil)`

Sorry, I cannot reproduce this in the following Emacs version:

```
In GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars)
 of 2023-01-17 built on blc
Windowing system distributor 'The X.Org Foundation', version 11.0.12101004
System Description:	Ubuntu 22.04.2 LTS

Recent messages:
For information about GNU Emacs and the GNU system, type C-h C-a.

Configured using:
 'configure CC=gcc-12 'CFLAGS=-O2 -march=native'
 --prefix=/home/bic/.local --with-file-notification=yes --with-modules
 --with-x --with-x-toolkit=lucid'

Configured features:
XAW3D XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS
GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT
ZLIB TOOLKIT_SCROLL_BARS LUCID X11 XDBE XIM MODULES THREADS LIBSYSTEMD
LCMS2

Important settings:
  value of $LC_MONETARY: en_IE.UTF-8
  value of $LC_NUMERIC: en_IE.UTF-8
  value of $LC_TIME: en_IE.UTF-8
  value of $LANG: en_GB.UTF-8
  value of $XMODIFIERS: @im=ibus
  locale-coding-system: utf-8-unix
```

> Was able to work-around this bug by commenting out "enable-recursive-minibuffers nil" -line:
> 
> ```
> (use-package ivy
>   :ensure t
>   :init (ivy-mode 1)
>   :bind (("C-c C-r"     . 'ivy-resume)             ;; remember/return to last session
>          ;;("<tab>"       . 'ivy-partial-or-done)    ;;MUST DEFINE in IVY-MB-MAP
> 	 ;;("C-j"         . 'ivy-alt-done)           ;;MUST DEFINE in IVY-MB-MAP
> 	 ;;("<backtab>"   . 'ivy-partial)            ;;TODO: what is this for?
> 	 ("C-x b"       . 'ivy-switch-buffer))     ;;
>   :config (setq ivy-use-virtual-buffers t
> 		;;enable-recursive-minibuffers nil
> 		ivy-use-selectable-prompt t
> 		ivy-display-style 'fancy
> 		ivy-count-format "(%d/%d) "
> 		ivy-wrap t)
>   (define-key ivy-minibuffer-map (kbd "<tab>") 'ivy-partial-or-done)
>   (define-key ivy-minibuffer-map (kbd "C-j") 'ivy-alt-done)
>   (define-key ivy-minibuffer-map (kbd "<backtab>") 'ivy-partial)
>   )
> ```

I tried both `make plain`, and `make plain` followed by applying this configuration, to no avail.

If you can reproduce the problem, please open a new issue, ideally with more detailed steps of what you press at each stage (e.g. what is `C-s` bound to? Do you insert `** ` or `\*\* `, etc.) and if possible, starting from `emacs -Q` or `make plain`, to rule out other parts of your configuration interfering.
